### ISSUE TITLE
Demo improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cosep#1]
- [x] 1. One can conveniently add port constraints but cannot delete existing ones. Can we add support for that?
- [x] 2. Are nodes assumed to be allowed to rotate by default? In any case, I think we should provide a way for node rotations to be specified through the user interface.
- [x] 3. It is nice to be able to export and import back as .json file but the output is not human readable since there is no *line break*. Can we add line breaks to make them more readable? Let's also rename these buttons as "Import constraint from file" and "Export constraint to file".
- [x] 4. Add a new button for importing sample constraints (a set that can be used for testing)
- [x] 5. Let's put a legend at the end of the Port Info tab to define what each arrow head means.
- [x] 6. How about using color on arrows to separate sources and targets of edges? So if source (target) of an edge is side constrained for instance we use a fixed color for the source (target) arrow head. I am suggesting to color arrow heads independent from their edge line colors.
- [x] 7. Duration not updated for regular CoSE layout

**Comment by ugurdogrusoz** [comment]
1. Ctrl + click will not work on Mac. Besides it's not visible. How about adding a simple button in each line to delete?

3. Import / Export seems to work but rename: "Export constraints from a file" => "Export constraints to a file"

5. Not addressed

**Comment by alihanokka** [comment]
1. Added dynamic buttons to 'Port Info' and 'Node Rotation' tabs that deletes ports/changes rotation.
2. Exported .json constraints file now has line breaks.
3. Added arrow head (port) legend on the top-right. 
4. Fixed simple duration bug.
5. Renamed 'Export constraints from a file' to "Export constraints to a file".

**Comment by ugurdogrusoz** [comment]
Missing a legend for what each arrow type signifies. Everything else seems to be fixed.

**Comment by alihanokka** [comment]
Does the legend on the top-right not show up on mac?

**Comment by ugurdogrusoz** [comment]
Yes
