### ISSUE TITLE
Separate rotation and swap options

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cosep#10]
Currently, a single option controls whether or not nodes can be rotated or swapped during layout. However, one might allow rotations but not swaps. Let's separate these as two options.

**Comment by hasanbalci** [comment]
CoSEP now has two separate options for rotation and swap control: `nodeRotations` and `nodeSwaps`. Both options accept a function to be able to assign per node values and returns `true` as default.

**Comment by ugurdogrusoz** [comment]
@herencalik Please review and close if OK. README looks good. Check its usage in the demo as well.
