### ISSUE TITLE
Random graph data for testing

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cosep#3]
We have Rome benchmark graphs which are simple biconnnected planar graphs but don't have any port information. If we can't find any benchmark graph set with port information, let's think about how to add ports to these graphs.

We also need some random *compound* graphs. We need to add ports to these as well.

**Comment by alihanokka** [comment]
I found some benchmark graphs including Rome in this [website](http://www.graphdrawing.org/data.html) via a random [paper](https://link.springer.com/chapter/10.1007/978-3-642-25878-7_10) that referenced this site. However, there are no graphs with port information.  
As a way to experiment adding random ports, I have added a menu with several options. The absolute ports that are added have random port indexes and side ports can be one of [top, right, left, bottom, top/bottom, right/left].

**Comment by ugurdogrusoz** [comment]
Let's use a subset of the Rome graphs we have in chilay (verify that these are indeed a subset of the Rome graphs available on the Internet) and perform the following tests:
- make sure regular CoSE layout does not perform tree reduction either
- using the random port assignment scheme you have, assign random ports to each graph
- run CoSE and CoSE-P and get all statistics available in the demo in a sheet

The next step is probably changing the different parameters for creating random ports and re-measuring the metrics.
